### ISSUE TITLE
Support for dynamic type

### ISSUE THREAD

**Issue by pqt** [nickmessing/babel-plugin-jsx-v-model#13]
Had to make my component look ugly because I wanted to leverage this library but it throws and error if I use a prop.

At the markup level I apply a `type` to the form component and apply some conditionals if it's a password. It doesn't makes sense in my particular case to hard code each type along the way.

I assume this was a conscious decision but wanted to raise this point and possibly start a discussion around this because it's the one thing preventing me from using this plugin full scale (I love it btw, excellent job).

**Comment by nickmessing** [comment]
This plugin is getting re-written at the moment and getting under `@vuejs` namespace on NPM so it will no longer be updated, that are unfortunately no plans yet to support dynamic `type` for `<input />` element because it creates a huge overhead, however, I will add exception for one specific case - ternary type with text & password so this will work:
```js
const el = <input type={condition ? 'text' : 'password'} />
```
But that's the only thing supported only because `text` and `password` work exactly the same (there is difference with `checkbox` and `radio`), sorry for inconvenience but it's really hard to support *any* jsx expression in `input`'s `type`

**Comment by pqt** [comment]
Okay, sweet. I ended up using it anyways and running through the conditionals. I have no idea what kind of hoops you have to jump through to make this all work but of course appreciate the plugin to support `v-model`.

https://vimeo.com/268623150
